name: reviewdog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '~18.8.0'
      - run: npm install
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          workdir: 'src'